baseURL: /
languageCode: en-us
title: Headlamp
theme: kinvolk-generic
assetsDir: assets
copyright: Microsoft Inc. All Rights Reserved.
params:
  description: Headlamp is an easy to use and extensible Kubernetes web UI
  favicon: "favicon.png"
  productionURL: https://headlamp.dev
  social:
    - title: github
      url: 'https://github.com/kinvolk/headlamp'
      image: 'github-icon'
    - title: twitter
      url: 'https://twitter.com/headlamp_ui'
      image: 'twitter-icon'
    - title: mastodon
      url: https://fosstodon.org/@headlamp
  twitter: '@headlamp_ui'
  docs:
    github_edit_url: https://github.com/kinvolk/headlamp/edit/main/docs/
    issues_url: https://github.com/kinvolk/headlamp/issues/new?labels=kind/docs
    external_docs:
    - repo: https://github.com/kinvolk/headlamp.git
      name: "latest"
      branch: "main"
      dir: "docs"
  footer:
    navlist:
      - title: Community
        quicklinks:
          - title: Slack
            link: https://kubernetes.slack.com/messages/headlamp
          - title: Contribute
            link: https://headlamp.dev/docs/latest/contributing/
          - title: Github
            link: https://github.com/kinvolk/headlamp
      - title: Documentation
        link: /docs
        quicklinks:
          - title: In-cluster Deployment
            link: https://headlamp.dev/docs/latest/installation/in-cluster/
          - title: Desktop app installation
            link: https://headlamp.dev/docs/latest/installation/desktop/
          - title: Plugin development
            link: https://headlamp.dev/docs/latest/development/plugins/

menu:
  main:
    - name: Blog
      url: /blog
      identifier: blog
      weight: -500
    - name: Slack <span class="fas fa-external-link-alt"></span>
      url: https://kubernetes.slack.com/messages/headlamp
      identifier: install
      weight: -55
    - name: Docs
      url: /docs
      identifier: docs
      weight: -60
    - name: Github
      url: https://github.com/kinvolk/headlamp
      identifier: github
      weight: -50
      pre: github
